### ISSUE TITLE
Error Message by saving the calibration in the calibration tool

### ISSUE THREAD

**Issue by SyFiD** [muchimi/JoystickGremlinEx#161]
Hello,
I get the following error message when saving my calibration.

![grafik](https://github.com/user-attachments/assets/f5fb189c-817f-4d98-9dec-325f87421f76)

**Comment by muchimi** [comment]
Resolved in 16m8.  Good find. Also, hey, someone is using the calibration tool!

**Comment by muchimi** [comment]
Resolved in 
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m8.zip

**Comment by SyFiD** [comment]
Thank you also for this update.

**Comment by muchimi** [comment]
Were you able to verify it works now?

**Comment by SyFiD** [comment]
> Resolved in 16m8. Good find. Also, hey, someone is using the calibration tool!

Works perfectly now!
I will now use the calibration tool more often. 
I had previously used DIView as an alternative, but this one is a bit more convenient ;-)

**Comment by SyFiD** [comment]
But I still have a suggestion.
Perhaps it would be nice to be able to save the axes separately and also enter the values manually.
This is possible with DIView. Here you have to hold in position and then center.

**Comment by muchimi** [comment]
Ok I'll close this issue for now as it's resolved and we can add the axes separation as an enhancement.
I am not famliar with diview but I'll look it up.

**Comment by SyFiD** [comment]
Here is a video how DIVIew works.

https://www.youtube.com/watch?v=b3Ut4R1O-Sw
