### ISSUE TITLE
No display of the assignment of an axis or buttons

### ISSUE THREAD

**Issue by SyFiD** [muchimi/JoystickGremlinEx#168]
Hello muchimi,
I can no longer see the assignment of the buttons or axes immediately if I have assigned a button or axis with 'Remap' or 'Vjoy Remap', for example.
Only when I exit JG or go in and out of the options menu is the axis or button updated with the corresponding symbol or only then is it displayed. 
Even after activating the active profile, the assignment only appears after restarting JG.

Here is a video to better illustrate the problem.
https://github.com/user-attachments/assets/d2007673-f082-433f-acfd-2f119f7dc027

But that has worked before. I just had a different problem before.
Previously, I always had an error when updating the symbols, for example when I changed button 1 to button 2. Then the correct assignment of the key was only displayed after I had inserted a second action and deleted it again.
However, this error no longer seems to exist.

**Comment by muchimi** [comment]
Resolved in 16 hotfix m17
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m17.zip

**Comment by SyFiD** [comment]
Thanks for the update. So far, the assignment is now displayed.
However, the icon next to the button does not always show the current assignment. It is only updated when I select the button directly in the Vjoy remap window under Output or go to the options menu and close it again.
Here is another video:

https://github.com/user-attachments/assets/01c97548-b885-4a94-be28-f4eaeb02a43d


I know that's complaining at a high level, but it's still annoying if you rely on the display.
Does this also affect the printing of the assignment?

After that, I'm happy with JG Ex for now.
;-)
Thanks for your efforts!

**Comment by muchimi** [comment]
Try this:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m18.zip

**Comment by SyFiD** [comment]
Unfortunately, the error is still there when updating the display. 
But it's not that bad. I can also deal with it otherwise.

**Comment by muchimi** [comment]
Forced synchronize between the two ways to map buttons (legacy and new) and icon updates.
Try this:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m19.zip

**Comment by SyFiD** [comment]
Man, you are good! 
It works!
Now give yourself a break. 
But I think I'm going to take a break. 
I'm sure you've got better things to do than keep working on my problems ;-)
